{
 "title": "Bore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FIle Descriptor Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"bore\"} / process_max_fds{job=\"bore\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bytes Incomming",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "incoming_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bytes Outgoing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outgoing_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total TCP Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_connections", "legendFormat": "__auto" }
   ]
  },
  { "title": "Tunnel Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Incomming Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "incoming_bytes_per_second", "legendFormat": "traffic" }
   ]
  },
  {
   "title": "Outgoing Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "outgoing_bytes_per_second", "legendFormat": "traffic" }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "total_connections", "legendFormat": "TCP Connections" }
   ]
  },
  { "title": "Rust Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"bore\"} / 1024 / 1024",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"bore\"} / 1024 / 1024",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "process_threads", "legendFormat": "process" }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"bore\"}",
     "legendFormat": "Available Descriptors"
    },
    {
     "expr": "process_max_fds{job=\"bore\"}",
     "legendFormat": "Used Descriptors"
    }
   ]
  }
 ]
}